USE MASTER
GO
CREATE DATABASE SERVIDOR_EFETIVO

CREATE LOGIN usr_servidorefetivo WITH PASSWORD='usr_servidorefetivo', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF

USE SERVIDOR_EFETIVO
GO
CREATE USER usr_servidorefetivo FOR LOGIN usr_servidorefetivo
GO

CREATE LOGIN usr_servidorefetivo_bi WITH PASSWORD='usr_servidorefetivo_bi', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF

USE SERVIDOR_EFETIVO
GO
CREATE USER usr_servidorefetivo_bi FOR LOGIN usr_servidorefetivo_bi
GO
